# -*- coding: utf-8 -*-
"""11399

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJ18iu4ok2IVoZ6wqooAOC2lXDly1kxe
"""

count = int(input())
t = list(map(int, input().split()))
t_t = list()
sum = 0
total = 0
t = sorted(t)
for i in range(count):
  sum += t[i]
  t_t.append(sum)
for i in range(count):
  total += t_t[i]
print(total)