# -*- coding: utf-8 -*-
"""1330

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPnJTUPABvQbBZ6KrGYvkMeFp5LgLdhi
"""

a, b = map(int, input().split())
if a<b:
  print("<")
elif a>b:
  print(">")
else:
  print("==")