# -*- coding: utf-8 -*-
"""14681

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-O4PDhlijqcLisfrMoRx73dX282kk4g
"""

a = int(input())
b = int(input())

if a>0 and b>0:
  print("1")
elif a<0 and b>0:
  print("2")
elif a<0 and b<0:
  print("3")
else:
  print("4")