# -*- coding: utf-8 -*-
"""2480

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlBHEx5bNOL0LPB0fpS7a92R2r4ub-fh
"""

a,b,c = map(int, input().split())

if a==b==c:
  print(10000 + 1000*a)
elif a==b:
  print(1000+100*a)
elif a==c:
  print(1000+100*a)
elif b==c:
  print(1000+100*b)
else:
  print(max(a,b,c)*100)