# -*- coding: utf-8 -*-
"""2884

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yNLaazhYoyEIV4zVSj4w043zYXRH3QZz
"""

h, m = map(int, input().split())

if m >= 45 :
    print(h, m-45)
elif h == 0 and m < 45 :
    print(23, 15+m)
elif m < 45 :
    print(h-1, 15+m)