# -*- coding: utf-8 -*-
"""1026

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3ZrF0vuAMwyW1gbJpnZiqFKTTS3IWMM
"""

num = int(input())
a = list(map(int, input().split()))
b = list(map(int, input().split()))

a = sorted(a, reverse = True)
b = sorted(b)

tot = 0
for i in range(num):
  tot += a[i]*b[i]

print(tot)