# -*- coding: utf-8 -*-
"""10172

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fy-WuySXDtHB340x3lDoQGLXWUSoQQGK
"""

print('|\\_/|\n|q p|   /}\n( 0 )"""\\\n|"^"`    |\n||_/=\\\\__|')