# -*- coding: utf-8 -*-
"""10171

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1raCKkqsDEGx7KLgrvBczaKG1nZRuIqvK
"""

print("\\    /\\ \n )  ( ')\n(  /  )\n \\(__)|")