# -*- coding: utf-8 -*-
"""10718

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_MVBAD3pOZIi5lsTznjHVzfecEky-03
"""

print("강한친구 대한육군\n강한친구 대한육군")