# -*- coding: utf-8 -*-
"""10869

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7cCcUjmA0K9yuc-KR8Ds63O1-W-bkSH
"""

a,b = map(int, input().split())

print(a+b)
print(a-b)
print(a*b)
print(int(a/b))
print(a%b)