# -*- coding: utf-8 -*-
"""10926

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvpEw6Co8sLFh9OjLP2yxQnCRePpbSsO
"""

len = input()
print(len+"??!")