# -*- coding: utf-8 -*-
"""18108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsKqXv2NLYbhT1g7kWVUSE1ubRp-neRN
"""

year = int(input())
print(year-543)