# -*- coding: utf-8 -*-
"""2588

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgXtHeDFbVLP5hJxy3ntDgtI6g3K7ewm
"""

A = input()
B = input()

print(int(A)*int(B[2]))
print(int(A)*int(B[1]))
print(int(A)*int(B[0]))
print(int(A)*int(B))