# -*- coding: utf-8 -*-
"""2438

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uwUe3pmR1FGA-2kxfHLg7pDJWkr5uIv
"""

inp = int(input())
for i in range(1,(inp+1)):
    print("*" * i)