# -*- coding: utf-8 -*-
"""2739

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HH0x09SlX5rVDu5wdIbH-0IXTJ0NJcB3
"""

num = int(input())

for i in range(1,10):
  print(num,"*",i,"=",num*i)